
export const LOADING = 'LOADING';
export const LOADINGSTOP = 'LOADINGSTOP';
export const AUTHREGISTER = 'AUTHREGISTER';
export const LOADINGPASSWORD = 'LOADINGPASSWORD';
export const AUTHLOGIN = 'AUTHLOGIN';
export const AUTHLOGOUT = 'AUTHLOGOUT';
export const AUTHPROFILEUP = 'AUTHPROFILEUP';
export const AUTHPROFILEPASSWORD = 'AUTHPROFILEPASSWORD';
export const AUTHDELETE = 'AUTHDELETE';
export const ERROR = 'ERROR';
